# Generated by Django 3.2.8 on 2021-11-27 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_movie_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='Product',
        ),
    ]
