# Generated by Django 3.2.8 on 2021-11-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_movie_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='averageRating',
            field=models.FloatField(verbose_name='Đánh Giá'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cast',
            field=models.CharField(max_length=800, verbose_name='Diễn Viên Nổi Bật'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=5000, verbose_name='Tóm Lược Nội Dung'),
        ),
        migrations.AlterField(
            model_name='product',
            name='director',
            field=models.CharField(max_length=300, verbose_name='Đạo Diễn'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(default=None, null=True, verbose_name='Ảnh Sản Phẩm'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Tên Sản Phẩm'),
        ),
        migrations.AlterField(
            model_name='product',
            name='release_date',
            field=models.DateField(verbose_name='Ngày Công Chiếu'),
        ),
    ]
