# Generated by Django 3.2.8 on 2021-11-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='averageRating',
            field=models.FloatField(default=0.0, editable=False, verbose_name='Đánh Giá'),
        ),
    ]
