# Generated by Django 3.2.8 on 2021-11-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_product_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.FileField(null=True, upload_to='link', verbose_name='Trailer'),
        ),
    ]
