# Generated by Django 3.2.8 on 2021-11-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_product_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.URLField(default=None, null=True, verbose_name='Trailer'),
        ),
    ]
