# Generated by Django 3.2.8 on 2021-11-28 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_product_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.FileField(null=True, upload_to='movie', verbose_name='File Movie')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
        ),
    ]
