# Generated by Django 3.2.8 on 2021-11-28 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_watchmovie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WatchMovie',
        ),
    ]
