# Generated by Django 3.2.8 on 2021-12-02 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_product_averagerating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='averageRating',
            field=models.FloatField(default=0.0, verbose_name='Đánh Giá'),
        ),
    ]
