# Generated by Django 3.2.8 on 2021-12-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_product_averagerating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_views',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Lượt Xem'),
        ),
    ]
