# Generated by Django 3.2.8 on 2021-12-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_product_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='num_like',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Lượt Thích'),
        ),
    ]
