# Generated by Django 3.2.8 on 2021-12-06 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_product_num_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='num_like',
        ),
    ]
