# Generated by Django 3.2.8 on 2021-12-06 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_product_num_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created',
        ),
    ]
