# Generated by Django 3.2.8 on 2021-12-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_remove_video_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='name',
            field=models.CharField(default=None, max_length=300),
            preserve_default=False,
        ),
    ]
