# Generated by Django 3.2.8 on 2021-12-12 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_listtypes_typeproduct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListTypes',
            new_name='ListType',
        ),
    ]
