# Generated by Django 3.2.8 on 2021-12-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_rename_listtypes_listtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeproduct',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
