# Generated by Django 3.2.8 on 2021-12-12 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_typeproduct_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typeproduct',
            old_name='name',
            new_name='types',
        ),
    ]
