# Generated by Django 3.2.8 on 2021-12-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20211212_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='Trailer'),
        ),
    ]
