# Generated by Django 3.2.8 on 2021-12-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_product_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='epnums',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Số Tập'),
        ),
        migrations.AddField(
            model_name='product',
            name='timeep',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Thời Lượng'),
        ),
    ]
